name: Create Release

on:
  release:
    types:
      - released
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release version (1.0.0)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Create release branch from develop
        run: |
          git checkout -b release/${{ github.event.release.tag_name }}

      - name: Set Maven version to release tag
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

      - name: Commit and push release version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "chore: set release version ${{ github.event.release.tag_name }}"
          git push origin release/${{ github.event.release.tag_name }}

      - name: Merge release branch to main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff release/${{ github.event.release.tag_name }} -m "Merge release ${{
            github.event.release.tag_name }} to main"
          git push origin main

      - name: Merge release branch back to develop
        run: |
          git checkout develop
          git pull origin develop
          git merge --no-ff release/${{ github.event.release.tag_name }} -m "Merge release ${{
            github.event.release.tag_name }} to develop"
          git push origin develop

      - name: Bump version to next SNAPSHOT
        run: |
          # Strip patch and bump minor (e.g. 1.2.3 -> 1.3.0-SNAPSHOT)
          VERSION=${{ github.event.release.tag_name }}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          NEXT_MINOR=$((MINOR + 1))
          NEXT_VERSION="$MAJOR.$NEXT_MINOR.0-SNAPSHOT"
          mvn versions:set -DnewVersion=$NEXT_VERSION

      - name: Commit and push next snapshot version
        run: |
          git commit -am "chore: prepare for next development iteration"
          git push origin develop