name: GitFlow Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 1.2.0)'
        required: true
      development_version:
        description: 'Next development version (e.g., 1.3.0-SNAPSHOT) '
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Git
        run: |
          git config user.name "Sajid-Nawaz-Ch"
          git config user.email "sajid.chaudhry.extern@dvag.com"

      - name: Run gitflow:release-start
        run: |
          mvn gitflow:release-start \
            -DreleaseVersion=${{ github.event.inputs.release_version }} \
            -DdevelopmentVersion=${{ github.event.inputs.development_version }} \
            -DpushRemote=true \
            -B

      - name: Push release branch
        run: |
          git push --all
          git push --tags

      - name: Run gitflow:release-finish
        run: |
          mvn gitflow:release-finish -DpushRemote=true -B
